Feature/encoder
HephaestusProject/pytorch-transformer pull request #7
Opened 2020-09-18 08:02 UTC by inmoonlight

# Pull Request
레파지토리에 기여해주셔서 감사드립니다.

해당 PR을 제출하기 전에 아래 사항이 완료되었는지 확인 부탁드립니다:
- [ ] 작성한 코드가 어떤 에러나 경고없이 빌드가 되었나요?
- [ ] 충분한 테스트를 수행하셨나요?

## 1. 해당 PR은 어떤 내용인가요?

Transformer encoder

## 2. PR과 관련된 이슈가 있나요?

#1

2020-09-18 09:38 UTC, ssaru commented on src/dataset.py
> +    def process(
`collate` -> `process`라고 이름을 변경하신 김에
어떤 process인지 함수 이름에 넣어주시면 더 많은 의미를 담을 수 있을 것 같습니다.

2020-09-18 11:40 UTC, ssaru commented on src/transformer.py
> +        padding_idx = tokenizer.token_to_id("<pad>")
이런거는 앞에 타입을 적어주면 읽는 사람에게 도움이 될 것 같습니다.

```python
        config: omegaconf.DictConfig = get_configs("model", "tokenizer", langpair=langpair)
        self.dim_model: int = config.model.train_params.dim_model
        self.vocab_size: int = config.tokenizer.vocab_size
        tokenizer: ??? = load_tokenizer(config.tokenizer)
        padding_idx: int = tokenizer.token_to_id("<pad>")
```

2020-09-18 11:41 UTC, ssaru reviewed
@inmoonlight 
코멘트 완료하였습니다!

2020-09-21 14:05 UTC, aisolab requested changes

2020-09-21 14:05 UTC, seopbo commented on src/dataset.py
> +    def process(
전체 로직을 보고 말씀드립니다. 개인적으로 source sequence, target sequence에 대한 preprocessor (tokenze, encode, decode를 하는 객체)는 `Dataset` class의 내부에서 구현되는 게아니라 외부에서 구현되어 instantiate되고`Dataset` class 내부에서 활용 시, 주입되어야 한다고 생각합니다. 실제 inference를 할 때는 `Dataset` class가 필요 없을 테니까요. @ssaru 마틴은 어떻게 생각하시나요?

2020-09-21 14:05 UTC, aisolab commented on src/dataset.py
> +    def process(
저보다 `nmt`에 조예가 깊으시기에 제가 코멘트 하는게 좀 걸리긴 하지만 저는 이런식으로 활용했었습니다. (과거 구현시)

```python
import pandas as pd
import torch
from torch.utils.data import Dataset
from torch.nn.utils.rnn import pad_sequence
from typing import List, Tuple


class NMTCorpus(Dataset):
    def __init__(self, filepath, src_transform_fn, tgt_transform_fn):
        self._corpus = pd.read_csv(filepath, sep='\t')
        self._src_transform = src_transform_fn
        self._tgt_transform = tgt_transform_fn

    def __len__(self):
        return len(self._corpus)

    def __getitem__(self, idx):
        list_of_source = torch.tensor(self._src_transform(self._corpus.iloc[idx]['ko']))
        list_of_target = torch.tensor(self._tgt_transform(self._corpus.iloc[idx]['en']))
        return list_of_source, list_of_target


def batchify(data: List[Tuple[torch.Tensor]]) -> Tuple[torch.tensor]:
    source_mb, target_mb = zip(*data)
    source_mb = pad_sequence(source_mb, batch_first=True, padding_value=1)
    target_mb = pad_sequence(target_mb, batch_first=True, padding_value=1)
    return source_mb, target_mb
```

2020-09-22 01:49 UTC, ssaru commented on src/dataset.py
> +    def process(
@aisolab 
> 개인적으로 source sequence, target sequence에 대한 preprocessor (tokenze, encode, decode를 하는 객체)는 Dataset class의 내부에서 구현되는 게아니라 외부에서 구현되어 instantiate되고Dataset class 내부에서 활용 시, 주입되어야 한다고 생각합니다.

네네. 저도 그런 방식을 생각하긴 했습니다.
객체를 주입할 수도 있을 것 같구요, 함수를 넣어서 해결할 수도 있을 것 같습니다.
다만, 제가 NLP쪽에는 조예가 깊지 못해서 NLP하시는 분들의 의견을 들어보고싶었습니다.

2020-09-27 03:22 UTC, inmoonlight commented on src/dataset.py
> +    def process(
@ssaru @aisolab 두 분 코멘트 감사해요 ㅋㅋㅋ 반영해서 수정하겠습니다!

2020-10-01 03:49 UTC, inmoonlight commented on src/transformer.py
> +        padding_idx = tokenizer.token_to_id("<pad>")
말씀하신대로 수정하다보니 아래의 이유로 type hinting이 필요할까? 라는 생각이 들었어요. 보시고 코멘트주세요! ㅎㅎ

1. 코드가 지저분해진다는 느낌을 받습니다.
2. 저는 타입이 변수명에서 드러난다는 생각이 듭니다.

2번 관련해서 혹시 마틴님은 어떤 부분에서 가독성이 떨어지셨나요?

2020-10-02 15:08 UTC, ssaru commented on src/transformer.py
> +        padding_idx = tokenizer.token_to_id("<pad>")
일괄적으로 모두 적어야한다고 생각하지는 않았습니다!
PR을 확인하기 전에 제 주관적인 생각을 말씀드리자면,,,

1. `config: omegaconf.DictConfig = get_configs("model", "tokenizer", langpair=langpair)`
이 경우에는 `config`이 `dict`인지 `omegaconf.DictConfig`인지에 따라서 변수를 사용하는 접근이 달라질 것 같다는 느낌을 받았습니다. 이때 함수명이 단순히 `get_configs`이기 때문에 어떤 타입의 변수가 반환될지 모른다는 느낌이 있었습니다.

2. `self.dim_model: int = config.model.train_params.dim_model`, `self.vocab_size: int = config.tokenizer.vocab_size`
이 경우는 여러 오픈소스 혹은 라이브러리에서 dimension이나 size를 표현하는 타입이 `int`, `tuple`, `list` 형태로 표현될 수 있기 때문이라고 생각했습니다.

사용자 입장에서는 코드상으로만 봤을 때는 해당 파라미터가 어떤 데이터 타입인지 알 수 없어 print를 찍어보거나, yaml파일을 봐야한다고 생각했습니다.

3. `tokenizer: ??? = load_tokenizer(config.tokenizer)`
토크나이져의 경우 어떤 객체타입을 주로 쓰는지 제가 잘 몰라서 적긴했습니다,,, ㅎㅎ

4. `padding_idx: int = tokenizer.token_to_id("<pad>")`
이 경우는 `idx`라는 이름에서 대부분 int를 쓰는 경우가 많기 때문에 오해의 소지가 없긴했는데요.
간혹 `indexes`형태의 복수를 쓰게되면 이게 tuple인지 list에 따라서 또 달라질 것 같습니다.

2020-10-02 15:11 UTC, ssaru commented
@inmoonlight 
지형님! 혹시 PR 반영을 완료하신 것이라면, 멘션으로 걸어주시면
"제가 PR을 봐야하는구나!"라고 인지하기 더 좋을 것 같습니다! ㅎㅎ
아니면 슬랙 DM으로 쪼아주셔도 저는 좋습니다! ㅋㅋㅋㅋ
(제가 보틀넥이 될까 무섭네요 ㅠㅠ)

2020-10-02 15:14 UTC, ssaru commented on src/data/data_utils.py
> +            continue
이런 부분까지 codecov를 요구하는군요! ㄷㄷㄷ

2020-10-02 15:16 UTC, ssaru commented on src/data/dataset.py
> +            raise ValueError(
여기도 codecov가!! ㅋㅋㅋㅋ
```
src/data/dataset.py#L40
Added line #L40 was not covered by tests
```

2020-10-02 15:21 UTC, ssaru commented on src/dataloader.py
> +                source_sample_lens, target_sample_lens = [source_sample_lens[-1]], [
여기가 code cov안됬다는 것은 또 신기하네요.
```
Added lines #L74 - L77 were not covered by tests
```

2020-10-02 15:21 UTC, ssaru commented on src/dataloader.py
> +                indices_batches.append(indices_batch)
여기도 test 코드 내에서 해당조건에 대한 테스트 구문이 없는 것 같네요! ㅎㅎ

2020-10-02 15:27 UTC, ssaru commented on src/utils.py
>      return config
분기가 많아져서 코드가 복잡해지는 것 같은데..... 
형준님 이번에 PR하신거에 Config에 빌더패턴을 적용하셨던데 이를 고려해보시면 어떠실까요?

https://github.com/HephaestusProject/pytorch-ReCoSa/pull/11#discussion_r498861049

2020-10-02 15:28 UTC, ssaru reviewed
@inmoonlight 

코멘트 완료하였습니다.
아우야... 테스트 코드를 완전 촘촘하게 짜셨군요! 

본받겠습니다.

2020-10-04 14:09 UTC, inmoonlight commented on src/transformer.py
> +        padding_idx = tokenizer.token_to_id("<pad>")
@ssaru 마틴님 상세한 답변 정말 감사해요! 😍 

답변에 대한 제 생각을 정리해봤어요 ㅎㅎ 미리 결론을 말하자면 **"코드를 읽는 과정에서 혼동의 여지가 큰 경우에 대해서만 type hinting을 적는다"** 입니다.

1. `config`의 경우 `dict`, `omegaconf.DictConfig` 인지에 따라 변수를 "사용"하는 접근이 달라질 수 있는데요, 사용법에 관계없이 읽는데에는 문제없을 거라 생각해서 가독성이 떨어지는 type hinting 을 사용하지 않는 것이 좋을 것 같다는 생각입니다. "model과 tokenizer에 관련된 configuration 을 불러온다" 정도의 내용이 전달되면 무관하다고 생각했습니다.

2. `dim_model` 이 경우는 `int`를 표기하는 것이 좋을 것 같습니다. tuple, list 의 형태를 기대할 수 있다고 생각해요. 다만 `vocab_size`는 글의 내용에서 int 인 것이 명확하므로 type hinting을 하지 않는 방향으로 정했습니다.

3. `tokenizer`는 사용한 tokenizer에 따라 객체 타입이 다를텐데요 (huggingface/tokenizer, google/sentencepiece 등) 1과 마찬가지로 읽는데에는 문제가 없으므로 표기하지 않으려고 합니다.

4. `idx` 네, 그래서 복수형을 사용하지 않았습니다 ㅎㅎ 객체명에서 바로 int 인 것이 드러날 수 있도록요.

2020-10-04 14:30 UTC, inmoonlight commented on src/utils.py
>      return config
@ssaru 오!! 매우 좋은 방법이 있었네요! ㅋㅋㅋ 마틴님 최고...

2020-10-05 16:56 UTC, ssaru commented on src/transformer.py
> +        padding_idx = tokenizer.token_to_id("<pad>")
@inmoonlight 넵넵 알겠습니다! ㅎㅎ
작업하시고 완료되면 멘션 걸어주세요~!

2020-10-06 00:09 UTC, inmoonlight commented
@ssaru @aisolab test code 작성 외에는 리뷰 반영 하였습니다! ㅋㅋㅋㅋㅋ test code는.. 조금 우선순위가 내려가서 커버리지가 90 이상이면 우선 넘어가고 마지막에 100으로 맞춰볼게요!

2020-10-11 03:07 UTC, aisolab commented on src/model/encoder.py
> +        return EncoderOut(
이부분에서 좀 궁금한점이 있습니다. `nn.Module`에 `forward`가 리턴하는 객체가 `custom class`나 지형님이 사용한 것과 같이 `NamedTuple`을 이용하여, 인터페이스를 위한 데이터 오브젝트를 정의할 경우, 이부분을 `DataLoader`의 `collate_fn`을 새롭게 정의해야하는 게 맞는 거겠죠?

2020-10-11 03:09 UTC, aisolab commented on src/model/modules.py
> +        self.register_buffer(
`hook`을 사용한 것인가요? 혹시 설명부탁드려도 될까요? (`PyTorch`에 조예가 깊으신 지형님!

2020-10-11 03:11 UTC, aisolab approved these changes
전체적으로 훑고 코멘트 남겼습니다. LGTM!

2020-10-13 11:26 UTC, ssaru commented on src/utils.py
> +        return self.configs.model
오 property 너무 좋네요!

2020-10-13 11:28 UTC, ssaru commented on src/model/modules.py
> +        self.register_buffer(
모듈 안에 변수를 넣는 방식인 것 같습니다.

https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.register_buffer

2020-10-13 11:32 UTC, ssaru commented on src/model/encoder.py
> +        return EncoderOut(
재밌는 컨셉이네요. 저도 와드! ㅎㅎ

2020-10-13 11:33 UTC, ssaru approved these changes
@inmoonlight 

LGTM
재밌게 잘봤습니다.
코드에 대한 고민을 많이 하신듯 보입니다.

2020-10-17 07:15 UTC, inmoonlight commented
추후 테스트코드 짜는 것을 잊지 않기 위한 이슈: https://github.com/HephaestusProject/pytorch-transformer/issues/10

2020-10-17 07:18 UTC, inmoonlight commented on src/model/encoder.py
> +        return EncoderOut(
@aisolab encoder는 나중에 transformer 전체 조립을 할 때 불러다 쓰는 용도라서요 ㅎㅎ `transformer.py`에서 data inout 의 형태가 결정될 것 같아요 (제가 질문을 잘 이해했는지 확신이 안드네요)

2020-10-17 07:23 UTC, aisolab commented on src/model/modules.py
> +        self.register_buffer(
@ssaru 오 아예 내부에 저런식으로 넣는군요 이해했사옵니다.

2020-10-17 07:28 UTC, inmoonlight commented on src/model/modules.py
> +        self.register_buffer(
@aisolab 이미 @ssaru 님이 잘 설명해주신 것 같은데요, 보통 파이토치로 모델을 짜면 학습하는 부분에 대해서만 모듈이 저장되는데요, positional encoding 의 경우 학습하는 부분은 아니지만 transformer 모델 구조에서 중요한 부분을 차지하고 있어서 buffer로 넣어주었습니당

2020-10-17 07:29 UTC, merged